#%RAML 1.0 DataType

displayName: controlType
type: string
enum: [TCT_ATM_WITHDRAW, TCT_AUTO_PAY, TCT_BRICK_AND_MORTAR, TCT_CROSS_BORDER, TCT_E_COMMERCE, TCT_FUNDS_TRANSFER, TCT_CONTACTLESS, MCT_ADULT_ENTERTAINMENT, MCT_AIRFARE, MCT_ALCOHOL, MCT_APPAREL_AND_ACCESSORIES, MCT_AUTOMOTIVE, MCT_CAR_RENTAL, MCT_ELECTRONICS, MCT_ENTERTAINMENT_AND_SPORTINGEVENTS, MCT_GAMBLING,MCT_GAS_AND_PETROLEUM, MCT_GROCERY, MCT_HOTEL_AND_LODGING, MCT_HOUSEHOLD, MCT_PERSONAL_CARE, MCT_RECREATION, MCT_SMOKE_AND_TOBACCO]
example: 'MCT_RECREATION'
description: Indicates the specific type of the control for Transaction Controls valid values begin with - 'TCT_', for MerchantControls valid values begin with - 'MCT_'