#%RAML 1.0 DataType

displayName: declineThreshold
type: number
format: double
example: 100
description: 'Decline threshold amount in issuing bank currency. If cardholderBillAmount exceeds this amount, all qualifying transactions for this control will receive a decline recommendation from VTC.'
