#%RAML 1.0 DataType
displayName: documentIDType
type: string
description: System generated ID of the Transaction Control Document bound to Account Identifier (primaryAccountNumber/bankAccountNumber/paymentToken)- The documentID of the transaction control document to be returned.
example: ctc-vd-857a8766-160b-498d-820f-bf4339949c1b