#%RAML 1.0 DataType
displayName: iscallBackEndpointLocalType
required: false
type: boolean
description: This value indicates whether callback URL is on a local network, Default is false will be send via WSI
example: true