#%RAML 1.0 DataType

displayName: isControlEnabled
example: true
description: 'If the indicator is set to true, the control is considered active. If set to false, the control is not checked by the authorization engine.'
type: boolean