#%RAML 1.0 DataType

displayName: shouldAlertOnDecline
example: true
description: 'If the indicator is set to true, and the alerting service is enabled, and a decision type of "COMPLETE" is received and the transaction is "DENIED", an alert message will be posted to the application ID Callback endpoint'
type: boolean