#%RAML 1.0 DataType
displayName: shouldTargetSpecificCardType

type: boolean
description: If the indicator is set to true, card details are required and card details will be used to locate a transaction control.
example: false