#%RAML 1.0 DataType

displayName: type
example: LMT_MONTH
description: 'Time period that the control spans.Valid values include LMT_MONTH, LMT_WEEK, LMT_DAY. This is a ENUM LIST'
type: string
enum: [LMT_MONTH, LMT_WEEK, LMT_DAY]