#%RAML 1.0 DataType
displayName: userIdentifierType
type: string
description: The UserIdentifier is a mandatory data element when supporting VTC notifications. It is used by the issuer -or their notification service provider- to uniquely identify the cardholder who has requested the alert message.
example: Abhishek