#%RAML 1.0 DataType
displayName: callBackEndpointType
required: true
type: string
minLength: 6
maxLength: 150
description: The alert notification callback URL, must be minimum 6, maximum of 150 charcters long
example: https://localhost:8080/sampleVCTChostprocessor/consumertransactioncontrols/testit