#%RAML 1.0 DataType

displayName: currentPeriodSpendType
format: double
example: 14.0
description: 'Total of all transactions that were approved, which qualify to trigger this control. This control is reset to the amount of the first approved transaction that is approved after the currentPeriodEndTime is observed.'
type: number