#%RAML 1.0 DataType
displayName: declineAllNonTokenizeTransactionsType
required: false
type: boolean
description: If the indicator is set to true, all non-tokenize transactions will be blocked.
example: false