#%RAML 1.0 DataType

displayName: endTime
example: Example
description: 'Ending time of a time range bounding the control. Only transactions attempted during the specified timeRange will trigger this control. If the endTime is less than the startTime, then the endTime is for the next day. The format of the string is in 24hr time using HH:MM format, and should reflect GMT time.'
type: string