#%RAML 1.0 DataType
displayName: primaryAccountNumber
description: Get Transaction Control Document List by a PrimaryAccountNumber
type: string
minLength: 16
maxLength: 25
example: "4514170000000001"

