#%RAML 1.0 DataType

displayName: shouldDeclineAll
example: true
description: 'If the indicator is set to true, all qualifying transactions for this control will receive a decline recommendation. If set to false, other controls, like declineThreshold will be checked.'
type: boolean