#%RAML 1.0 DataType

displayName: startTime
example: '15:10'
description: 'Starting time of a time range bounding the control. Only transactions attempted during the specified timeRange will trigger this control. The format of the string is in 24hr time using HH:MM format, and should reflect GMT time.'
type: string