#%RAML 1.0 DataType

displayName: timeZoneID
example: Europe/Dublin
description: 'Determines the next currentPeriodEndTime based on spendLimitType. It supports default group IANA Time Zone Database (TZDB) and it should be in Area/Location format. For example ‘America/New_York’ represents most of the US Eastern Time Zone.'
type: string