#%RAML 1.0 DataType
displayName: callbackSettingsRequestType
required: true
description: callbackSettingsRequest
properties: 
  callBackSettings:
    type: !include baseTypes/callBackSettingsType.raml