#%RAML 1.0 DataType
description: Response resource container.
type: object
properties:
  status:
    required: true
    example: 'SUCCESS'
    description: 'Account Update Status Enum Values * SUCCESS'
    type: string