#%RAML 1.0 DataType
displayName: transactionControlListResponesResource
description: Response resource container.
type: object
properties: 
    controlDocuments:
      required: false
      type: !include baseTypes/controlDocumentsType.raml