#%RAML 1.0 DataType
displayName: accountInquiryByListResource
description: Response resource container.
type: object
properties:
    accountInquiryResponse:
      required: false
      type: !include baseTypes/accountInquiryResponseType.raml