#%RAML 1.0 DataType
displayName: changeHistroyOfAConsumerTCDResourceType
description: Response resource container.
properties:
  controlDocuments:
    required: false
    type: !include baseTypes/controlDocumentsType.raml